version: "3"

services:
  php:
    build: ./mockapp
    volumes:
      - ./mockapp:/code
  nginx:
    image: nginx
    ports:
      - "9001:80"
    expose:
      - 80
    volumes:
      - ./mockapp:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ta2"
      MYSQL_USER: "ta2"
      MYSQL_PASSWORD: "ta2"
    volumes:
      - ./mockapp/sql:/docker-entrypoint-initdb.d
  haproxy:
    build: ./
    ports:
      - "9000:80"
    expose:
      - 80
    depends_on:
      - "nginx"
